name: T-Evolvers Website Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Ejecutar todos los días a las 9:00 AM UTC (6:00 AM Colombia)
    - cron: '0 10 * * *'
  workflow_dispatch:
    # Permite ejecutar manualmente desde GitHub

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npx playwright test t-evolvers-validation.spec.ts
      
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - name: Upload Screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-screenshots
        path: tests/screenshots/
        retention-days: 30

    - name: Notify Teams on Success
      if: success()
      run: |
        curl -H "Content-Type: application/json" -d '{
          "@type": "MessageCard",
          "@context": "https://schema.org/extensions",
          "themeColor": "28a745",
          "summary": "T-Evolvers Website Tests - SUCCESS",
          "sections": [{
            "activityTitle": "✅ Website Validation Tests Passed",
            "activitySubtitle": "${{ github.repository }} - ${{ github.ref_name }}",
            "facts": [
              {
                "name": "Repository:",
                "value": "${{ github.repository }}"
              },
              {
                "name": "Branch:",
                "value": "${{ github.ref_name }}"
              },
              {
                "name": "Commit:",
                "value": "${{ github.sha }}"
              },
              {
                "name": "Triggered by:",
                "value": "${{ github.actor }}"
              },
              {
                "name": "Status:",
                "value": "✅ ALL TESTS PASSED"
              },
              {
                "name": "Website:",
                "value": "www.t-evolvers.com"
              }
            ]
          }],
          "potentialAction": [{
            "@type": "OpenUri",
            "name": "View Run Details",
            "targets": [{
              "os": "default",
              "uri": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }]
          }]
        }' ${{ secrets.TEAMS_WEBHOOK_URL }}

    - name: Notify Teams on Failure
      if: failure()
      run: |
        curl -H "Content-Type: application/json" -d '{
          "@type": "MessageCard",
          "@context": "https://schema.org/extensions",
          "themeColor": "dc3545",
          "summary": "T-Evolvers Website Tests - FAILED",
          "sections": [{
            "activityTitle": "❌ Website Validation Tests Failed",
            "activitySubtitle": "${{ github.repository }} - ${{ github.ref_name }}",
            "facts": [
              {
                "name": "Repository:",
                "value": "${{ github.repository }}"
              },
              {
                "name": "Branch:",
                "value": "${{ github.ref_name }}"
              },
              {
                "name": "Commit:",
                "value": "${{ github.sha }}"
              },
              {
                "name": "Triggered by:",
                "value": "${{ github.actor }}"
              },
              {
                "name": "Status:",
                "value": "❌ TESTS FAILED"
              },
              {
                "name": "Website:",
                "value": "www.t-evolvers.com"
              }
            ]
          }],
          "potentialAction": [{
            "@type": "OpenUri",
            "name": "View Failed Run",
            "targets": [{
              "os": "default",
              "uri": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }]
          }, {
            "@type": "OpenUri",
            "name": "Check Website",
            "targets": [{
              "os": "default",
              "uri": "https://www.t-evolvers.com"
            }]
          }]
        }' ${{ secrets.TEAMS_WEBHOOK_URL }}
